<MyRoot>


    cal_field: cal_field

    orientation: "vertical"
    TextInput:
        id: cal_field
        height: 200
        size_hint: (1, None)
        readonly: True
        disabled: True
        font_size: 64
    BoxLayout:
        orientation: "horizontal"
        padding: 10
        spacing: 10
        height: 100
        size_hint: (1, None)
        Button:
            text: "."
            font_size: 26
            on_press: root.cal_sym(".")
        Button:
            text: "C"
            font_size: 26
            on_press: root.clear()
        Button:
            text: "="
            font_size: 26
            on_press: root.equal()
        Button:
            text: "<-"
            font_size: 26
            on_press: root.backspace()
    GridLayout:
        rows: 4
        columns: 4
        padding: 10
        spacing: 10
        height: 400
        size_hint: (1, None)
        Button:
            text: "1"
            font_size: 26
            on_press: root.cal_sym("1")
        Button:
            
            text: "2"
            font_size: 26
            on_press: root.cal_sym("2")
        Button:
            text: "3"
            font_size: 26
            on_press: root.cal_sym("3")
        Button:
            text: "+"
            font_size: 26
            on_press: root.cal_sym("+")
        Button:
            text: "4"
            font_size: 26
            on_press: root.cal_sym("4")
        Button:
            text: "5"
            font_size: 26
            on_press: root.cal_sym("5")
        Button:
            text: "6"
            font_size: 26
            on_press: root.cal_sym("6")
        Button:
            text: "-"
            font_size: 26
            on_press: root.cal_sym("-")
        Button:
            text: "7"
            font_size: 26
            on_press: root.cal_sym("7")
        Button:
            text: "8"
            font_size: 26
            on_press: root.cal_sym("8")
        Button:
            text: "9"
            font_size: 26
            on_press: root.cal_sym("9")
        Button:
            text: "X"
            font_size: 26
            on_press: root.cal_sym("*")
        Button:
            text: "("
            font_size: 26
            on_press: root.cal_sym("(")
        Button:
            text: "0"
            font_size: 26
            on_press: root.cal_sym("0")
        Button:
            text: ")"
            font_size: 26
            on_press: root.cal_sym(")")
        Button:
            text: "÷"
            font_size: 26
            on_press: root.cal_sym("/")
    